--- #YAML:1.0
name:                Sort-Key-Radix
version:             0.01
abstract:            Radix sort implementation in XS
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Salvador Fandino <sfandino@yahoo.com>
